### PR TITLE
Laravel 11 updates

### PR DESCRIPTION
**Pull request by swapnilsarwe**
* Adding support for laravel 11
* removed unspported PHP version & Laravel version from tests matrix

### CODE REVIEW

**Comment by swapnilsarwe** [comment]
@Hasnayeen - have a look at MR & merge at your own convenience. No rush.

**Comment by Hasnayeen** [comment]
@swapnilsarwe Thanks for the PR.
Both php 7, 8.0 and Laravel 9 has reached end of life, so can you remove those from the test matrix, thank you.

**Comment by swapnilsarwe** [comment]
> @swapnilsarwe Thanks for the PR. Both php 7, 8.0 and Laravel 9 has reached end of life, so can you remove those from the test matrix, thank you.

you want me to update composer.json by removing support for PHP 7,8 & Laravel 8,9 too ?

**Comment by Hasnayeen** [comment]
> > @swapnilsarwe Thanks for the PR. Both php 7, 8.0 and Laravel 9 has reached end of life, so can you remove those from the test matrix, thank you.
> 
> you want me to update composer.json by removing support for PHP 7,8 & Laravel 8,9 too ?

Yes please.

**Comment by Hasnayeen** [comment]
@swapnilsarwe can you add `.php-fixer.cache` to `.gitignore`

**Comment by swapnilsarwe** [comment]
> @swapnilsarwe can you add `.php-fixer.cache` to `.gitignore`

done

**Comment by swapnilsarwe** [comment]
I recommend you should mark this as a new major release. Since a lot of deprecation.

**Comment by Hasnayeen** [comment]
> I recommend you should mark this as a new major release. Since a lot of deprecation.

Done

**Pull request merged**
